"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path # This is a Python module that provides an object-oriented interface for working with the file system.
from decouple import config # This is a Python module that helps you to separate the settings of your Django project from your source code.
import os # This module provides a portable way of using operating system dependent functionality.



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent # This is the base directory of the Django project.


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7v(!o&*h4o8jo#h@8du+i%^=!*_59cs419bvh^2y%)$9cvp1td'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # This is a boolean that turns on/off the debug mode of the Django project.

ALLOWED_HOSTS = ['*'] # This is a list of strings representing the host/domain names that this Django site can serve.

MEDIA_URL = '/media/' # This is the URL that handles the media files uploaded by the user.
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # This is the directory where the media files are stored.

CORS_ALLOWED_ORIGINS = [ # This is a list of strings representing the origin URLs that are allowed to make requests to this Django project.
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
CSRF_TRUSTED_ORIGINS = [ # This is a list of strings representing the origin URLs that are allowed to make CSRF requests to this Django project.
    "http://127.0.0.1:3000",  
]
CORS_ALLOW_CREDENTIALS = True # This is a boolean that allows the credentials to be included in the requests to this Django project.

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders', # This is the Django application that allows the Django project to handle the CORS requests.
    'rest_framework', # This is the Django application that provides the REST API framework for the Django project.
    'user_api.apps.UserApiConfig', # This is the Django application that provides the user model for the Django project.
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # This is the middleware that allows the Django project to handle the CORS requests.
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls' # This is the URL configuration of the Django project.

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}

## User model
AUTH_USER_MODEL = 'user_api.AppUser' # This is the user model of the Django project.

REST_FRAMEWORK = { # This is the configuration of the REST framework of the Django project.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/' # This is the URL that handles the static files of the Django project.
STATIC_ROOT = '/static/' # This is the directory where the static files are stored.

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
