# Generated by Django 5.1.1 on 2024-10-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestMode',
            new_name='TestModel',
        ),
    ]
