# Generated by Django 5.1.1 on 2024-10-07 12:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_message_preferencesheet_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='available_from',
            new_name='available_start_date',
        ),
        migrations.AddField(
            model_name='post',
            name='number_rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='preferencesheet',
            name='gender_preference',
            field=models.CharField(default='Any', max_length=6),
        ),
        migrations.AlterField(
            model_name='preferencesheet',
            name='smoking_preference',
            field=models.CharField(default='No Preference', max_length=15),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('matchid', models.AutoField(primary_key=True, serialize=False)),
                ('compatability_score', models.FloatField()),
                ('match_date', models.DateField(default=django.utils.timezone.now)),
                ('maybe_roommateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_matches', to=settings.AUTH_USER_MODEL)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('comment', models.TextField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
